 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     docker:
       - image: mcr.microsoft.com/dotnet/core/sdk:3.1     
     steps:
       - checkout
       - run:
          name: Dotnet Restore
          command:
            dotnet restore
       - run:
          name: Build App
          command: dotnet build
