 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
  build:
    working_directory: /src
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1  
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore src/Epila.Ph.Api/Epila.Ph.Api/Epila.Ph.Api.csproj
      - run: dotnet build src/Epila.Ph.Api/Epila.Ph.Api/Epila.Ph.Api.csproj